# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
#
obj-$(CONFIG_OF_SYSTEM_SETUP) += am62l3_fdt.o
obj-$(CONFIG_SPL_BUILD) += am62l3_init.o
obj-y += boot.o
